import type { FacilitySearchConfig } from "@/components/Facilities/FacilitySearchContent";

/**
 * Per-tool config for every government facility lookup under /tools that renders
 * via the shared `FacilitySearchContent` client component. Each page.tsx imports its
 * entry directly and passes it straight through — kept here as plain data (rather
 * than as one always-client wrapper component per facility type) since none of these
 * configs need state or hooks of their own.
 */
export const facilitySearchConfigs = {
  clinics: {
    facilityType: "clinic",
    emoji: "🏥",
    title: "醫療院所查詢",
    description: "查詢全民健保特約醫療院所。資料來源：衛福部中央健康保險署（目前收錄醫學中心、區域醫院、地區醫院）。",
    searchPlaceholder: "輸入院所名稱或縣市關鍵字",
    errorText: "查詢院所資料失敗，請稍後再試。",
    emptyStateNoKeyword: "附近查無已定位的院所，可改用關鍵字搜尋。",
    emptyStateWithKeyword: "查無符合的院所。",
    serviceItem: "badge",
    showWeeklyHours: true,
    categories: [
      { value: "醫學中心", label: "醫學中心" },
      { value: "區域醫院", label: "區域醫院" },
      { value: "地區醫院", label: "地區醫院" },
      { value: "基層診所", label: "基層診所" },
    ],
  },
  pharmacies: {
    facilityType: "pharmacy",
    emoji: "🏪",
    title: "藥局查詢",
    description: "查詢全台一般藥局及健保特約藥局。資料來源：衛福部食藥署藥局管理系統、中央健康保險署。",
    searchPlaceholder: "輸入藥局名稱或地址關鍵字（縣市、鄉鎮）",
    radiusMeters: 5000,
    errorText: "查詢藥局資料失敗，請稍後再試。",
    emptyStateNoKeyword: "附近 5 公里內查無已定位的藥局，可改用關鍵字搜尋。",
    emptyStateWithKeyword: "查無符合的藥局。",
    serviceItem: "badge",
    showWeeklyHours: true,
    showGeocodeNote: true,
    locationDefaultWarning: "⚠️ 無法取得您的定位，附近搜尋改用預設位置範圍；您也可以直接用上方關鍵字搜尋全台藥局。",
    categories: [
      { value: "健保特約藥局", label: "健保特約藥局" },
      { value: "一般藥局", label: "一般藥局" },
    ],
  },
  "hakka-community": {
    facilityType: "hakka_community",
    emoji: "🏘️",
    title: "客庄社區發展協會查詢",
    description: "查詢客家委員會客庄社區發展協會名冊。資料來源：客家委員會開放資料。",
    searchPlaceholder: "輸入協會名稱或縣市關鍵字",
    errorText: "查詢協會資料失敗，請稍後再試。",
    emptyStateNoKeyword: "附近查無收錄的客庄社區發展協會，可改用關鍵字搜尋。",
    emptyStateWithKeyword: "查無符合的協會。",
  },
  "ltc-contracted": {
    facilityType: "ltc_contracted",
    emoji: "🤝",
    title: "長照特約服務機構查詢",
    description: "查詢衛福部長照2.0特約服務機構，涵蓋居家服務、日間照顧、喘息服務等契約服務項目。資料來源：衛福部長照服務資訊網。",
    searchPlaceholder: "輸入機構名稱或縣市關鍵字",
    errorText: "查詢機構資料失敗，請稍後再試。",
    emptyStateNoKeyword: "附近查無收錄的長照特約服務機構，可改用關鍵字搜尋。",
    emptyStateWithKeyword: "查無符合的機構。",
    serviceItem: { label: "特約服務項目：" },
  },
  "elder-welfare": {
    facilityType: "elder_welfare",
    emoji: "👵",
    title: "老人福利機構查詢",
    description: "查詢衛福部全國老人福利機構名冊（安養、養護、長照等機構）。資料來源：衛福部社會及家庭署開放資料。",
    searchPlaceholder: "輸入機構名稱或縣市關鍵字",
    errorText: "查詢機構資料失敗，請稍後再試。",
    emptyStateNoKeyword: "附近查無收錄的老人福利機構，可改用關鍵字搜尋。",
    emptyStateWithKeyword: "查無符合的機構。",
    serviceItem: { label: "收容對象：" },
  },
  "disability-welfare": {
    facilityType: "disability_welfare",
    emoji: "🧑‍🦽",
    title: "身心障礙福利機構查詢",
    description: "查詢衛福部全國身心障礙福利機構名冊。資料來源：衛福部社會及家庭署開放資料。",
    searchPlaceholder: "輸入機構名稱或縣市關鍵字",
    errorText: "查詢機構資料失敗，請稍後再試。",
    emptyStateNoKeyword: "附近查無收錄的身心障礙福利機構，可改用關鍵字搜尋。",
    emptyStateWithKeyword: "查無符合的機構。",
    serviceItem: { label: "機構類型：" },
  },
  "health-checks": {
    facilityType: "health_check",
    emoji: "🩻",
    title: "健康檢查機構查詢",
    description: "查詢勞工健康檢查認可醫療機構及職業傷病防治網絡醫院。資料來源：勞動部。",
    noteLine: "⚠️ 老人免費健檢機構資料源目前無法連線，暫未收錄。",
    searchPlaceholder: "輸入機構名稱或縣市關鍵字",
    errorText: "查詢機構資料失敗，請稍後再試。",
    emptyStateNoKeyword: "附近查無已定位的機構，可改用關鍵字搜尋。",
    emptyStateWithKeyword: "查無符合的機構。",
    serviceItem: { label: "認可項目：" },
    showGeocodeNote: true,
  },
  "home-healthcare": {
    facilityType: "home_healthcare",
    emoji: "🏠",
    title: "居家醫療查詢",
    description: "查詢提供居家醫療照護服務的全民健保特約機構。資料來源：衛福部中央健康保險署。",
    searchPlaceholder: "輸入機構名稱或縣市關鍵字",
    errorText: "查詢機構資料失敗，請稍後再試。",
    emptyStateNoKeyword: "附近查無收錄的機構，可改用關鍵字搜尋。",
    emptyStateWithKeyword: "查無符合的機構。",
    serviceItem: "badge",
  },
  "long-term-care": {
    facilityType: "long_term_care",
    emoji: "🏡",
    title: "長照機構查詢",
    description: "查詢衛福部許可全台長期照顧服務機構。資料來源：衛福部長照服務地圖。",
    searchPlaceholder: "輸入機構名稱或縣市關鍵字",
    errorText: "查詢機構資料失敗，請稍後再試。",
    emptyStateNoKeyword: "附近查無收錄的長照機構，可改用關鍵字搜尋。",
    emptyStateWithKeyword: "查無符合的機構。",
  },
} satisfies Record<string, FacilitySearchConfig>;
